const genButton = () => document.getElementById("generatebutton")
const nounDisplay = () => document.getElementById("noun")
const prefixDisplay = () => document.getElementById("prefix")
const suffixDisplay = () => document.getElementById("suffix")
const versionDisplay = () => document.getElementById("version")
const countDisplay = () => document.getElementById("promptcount")

const version = "1.0.2"
const maxAdjectives = 3

const nouns = [
    "snakes",
    "dog",
    "vampire",
    "moose",
    "Donkey Kong",
    "Mario",
    "Lucario",
    "Johnny Bravo",
    "Augie Doggy",
    "Joey Wheeler",
    "Yugi",
    "Seto Kaiba",
    "Mai Valentine",
    "Yogi",
    "Jacob",
    "Julia",
    "Nathan",
    "Karina",
    "Shrek",
    "Garfield",
    "Odie",
    "Donkey",
    "Jotaro",
    "Joseph Joestar",
    "Polnareff",
    "Dio",
    "Josuke Higashikata",
    "Koichi Hirose",
    "Ryunosuke Naruhodo",
    "Ryu",
    "Ken",
    "Jimmy",
    "Frog",
    "Crab",
    "Goblin",
    "ChillChuck",
    "Laios",
    "Marcille",
    "Goofy",
    "Todd",
    "Possum",
    "Raymond",
    "Michael",
    "Mickey",
    "Kermit",
    "Elmo",
    "Adam Skate The Infinity",
    "Legoshi",
    "Agumon",
    "Garurumon",
    "Greymon",
    "Gatomon",
    "Angemon",
    "Angewomon",
    "Wizardmon",
    "Leomon",
    "Beelzemon",
    "Wolf",
    "Trunks",
    "Goku",
    "Vegeta",
    "Freiza",
    "Bulma",
    "Android 18",
    "Krillin",
    "Gohan",
    "Mug",
    "Goofy",
    "Scooby Doo",
    "Shaggy",
    "Velma",
    "Fred",
    "Daphne",
    "Dragon",
    "Flygon",
    "Bulbasaur",
    "Venusaur",
    "Snorlax",
    "Greninja",
    "Pikachu",
    "Mewtwo",
    "Goofy",
    "Gumby",
    "Zombie",
    "Gandalf",
    "Frodo",
    "Grover",
    "Cookie Monster",
    "Animal",
    "Yoda",
    "Link",
    "Zelda",
    "Ganondorf",
    "lawyer",
    "salaryman",
    "Queen",
    "King",
    "Knight",
    "Devil",
    "Dean Winchester",
    "Castiel",
    "Football Player",
    "Sandwich",
    "Wine Aunt",
    "Caillou",
    "Spheal",
    "Grinch",
    "Onceler",
    "Lorax",
    "Willy Wonka",
    "Charlie the Unicorn",
    "Smurf",
    "Homestar",
    "StrongBad",
    "Ghost",
    "Pokemon",
    "Barbie",
    "Mech",
    "Kaiju",
    "Cowboy",
    "Astarion",
    "Gale",
    "Karlach",
    "Shadowheart",
    "Lae'zel",
    "Capybara",
    "Hyena",
    "Elephant",
    "Miss Piggy",
    "Poop Emoji",
    "Seinfeld",
    "George Costanza",
    "Kramer",
    "Niles",
    "Frasier",
    "Homer Simpson",
    "Bart Simpson",
    "Marge Simpson",
    "Peter Griffin",
    "Brian Griffin",
    "Bob Belcher",
    "Gojo",
    "Skeleton",
    "Man",
    "Edward Cullen",
    "Bella Swan",
    "Charlie Swan",
    "Bugs Bunny",
    "Elmer Fudd",
    "Daffy Duck",
    "Bobby Hill",
    "Hank Hill",
    "Peggy Hill",
    "Dale Gribble",
    "Boomhauer",
    "Cookie Puss",
    "Fudgie the Whale",
    "Godzilla",
    "Kong",
    "Cheese",
    "Phoenix Wright",
    "Apollo Justice",
    "Miles Edgeworth",
    "Herlock Sholmes",
    "Godot",
    "Mario",
    "Luigi",
    "Peach",
    "Bowser",
    "Toad",
    "Goomba",
    "Majima",
    "Kiryu",
    "Mojo Jojo",
    "Doom Guy",
    "Megaman",
    "Zero",
    "Master Chief",
    "Black Lotus",
    "Villager",
    "Marth",
    "Ike",
    "Mr. Game and Watch",
    "Steamboat Willy",
    "Joker",
    "Batman",
    "SuperMan",
    "Spider-Man",
    "Ziggy",
    "Archie",
    "Jughead",
    "Takumi Fujiwara",
    "shop-keeper",
    "adventurer",
    "dragonborn",
    "dinosaur lie",
    "barista",
]

const beforeAdjectives = [
    "flat",
    "metal",
    "Powerpuff",
    "anime",
    "smooth",
    "buff",
    "cool",
    "nasty",
    "SFW",
    "Jojo's Bizarre",
    "salaryman",
    "colossal",
    "Charles Entertainment",
    "evil",
    "small",
    "steampunk",
    "edgelord",
    "Dr.",
    "Baron von",
    "sparkling",
    "big",
    "Sir",
    "pickle",
    "Jacob-",
    "elf",
    "orc",
    "dragonborn",
    "halfling",
    "sugar free",
    "Nuesday",
    "Mr.",
    "Mrs.",
    "sad",
    "haunted",
    "icky",
    "uncomfortable",
    "zesty",
    "old-timey",
    "oily",
    "stinky",
    "dangerous",
    "cat",
    "magical girl",
    "The Loathesome",
    "mechanical",
    "cheesy five-layer",
    "epic",
    "construction worker",
    "Final Fantasy",
    "cursed",
    "Michigan J.",
    "girlfail",
    "kaiju",
    "boyfail",
    "Twitch streamer",
    "influencer",
    "Pope",
    "Super-",
    "undead",
    "scared",
    "bodybuilder",
    "shaved",
    "were-",
    "soft alpha",
    "untenable",
    "silly",
    "yassified",
    "cozy",
    "tired",
    "divorced dad",
    "bumpy",
    "incorporeal",
    "noble",
    "classic",
    "hairy",
    "spikey",
    "grandiose",
    "opera",
    "friendly",
    "chibi",
    "foul",
    "ghost",
    "golden",
    "silver",
    "old",
    "antique",
    "Digimon",
    "chef",
    "Ratatouille",
    "dehydrated",
    "satiated",
    "calm",
    "stoner",
    "wired",
    "nervous",
    "weird",
    "necromancer",
    "catboy",
    "odd",
    "keyhole",
    "Family Guy",
    "gritty reboot",
]

const afterAdjectives = [
    "with legs",
    "gajinka",
    "fursona",
    "from memory",
    "and Doggy Daddy",
    "full of vampires",
    "made from cheese",
    "Animal Crossing",
    "The Second",
    "and Toad",
    "-Kong",
    ", Esquire",
    "-field",
    "in mortal peril",
    "the Frog",
    "Beastars",
    "from Mario",
    "with cheese",
    "but good",
    "but worse",
    "with a beard",
    "-Doo",
    "Pro",
    "-hunter",
    "GX",
    ", Ace Attorney",
    "to relax/study to",
    "Deluxe",
    "Game of the Year Edition",
    "voiced by Patrick Warburton",
    "from North America",
    "? ... Nasty",
]

function addPrefix(input) {
    let index = Math.floor(Math.random() * (beforeAdjectives.length))
    return input + ' ' + beforeAdjectives[index] 
}

function addSuffix(input) {
    let index = Math.floor(Math.random() * (afterAdjectives.length))
    return input + ' ' + afterAdjectives[index] 
}

function setPromptColor(amount) {
    let huePre = Math.floor(Math.random() * 255)
    prefixDisplay().style.color = 'hsl(' + huePre + ',100%, 40%)'
    let hueSuf = Math.floor(Math.random() * 255)
    suffixDisplay().style.color = 'hsl(' + hueSuf + ',100%, 40%)'
}

function addAdjective(input) {
    if ((Math.floor(Math.random() * (afterAdjectives.length + beforeAdjectives.length))) < beforeAdjectives.length) {
        return addPrefix(input)
    } else {
        return addSuffix(input)
    }
}

function generate() {
    let nounIndex = Math.floor(Math.random() * (nouns.length))
    var noun = nouns[nounIndex]
    var prefix = ""
    var suffix = ""


    let rand = Math.random()
    let weightedRand = Math.pow(rand, 6)
    let scaledRand = weightedRand * maxAdjectives
    let numberOfAdjectives = Math.floor(scaledRand)

    for (let i = 0; i<=numberOfAdjectives; i++) {
        if ((Math.floor(Math.random() * (afterAdjectives.length + beforeAdjectives.length))) < beforeAdjectives.length) {
            prefix = addPrefix(prefix)
        } else {
            suffix = addSuffix(suffix)
        }
    }

    setPromptColor()
    nounDisplay().textContent = noun
    prefixDisplay().textContent = prefix
    suffixDisplay().textContent = suffix
}

function getMaxPromptCount() {
    let numberOfAdjectives = beforeAdjectives.length + afterAdjectives.length
    let numberOfNouns = nouns.length
    let maxCombinations = Math.pow(numberOfAdjectives, maxAdjectives)*numberOfNouns
    return maxCombinations
}

genButton().addEventListener("click", generate)
countDisplay().textContent = getMaxPromptCount() + " possible prompts"
versionDisplay().textContent = "Version " + version

